name: CI Pipeline

on:
  push:
    branches:
      - main
      - prod
  pull_request:
    branches:
      - main
      - prod

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Récupère le code

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'  # Change si besoin

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y unzip git libsqlite3-dev zip

      - name: Run Tests
        run: mvn test